/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SetPinRouteImport } from './routes/set-pin'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PinRouteImport } from './routes/pin'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as NotRegisteredRouteImport } from './routes/not-registered'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingIdRouteImport } from './routes/booking.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPinRoute = SetPinRouteImport.update({
  id: '/set-pin',
  path: '/set-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotRegisteredRoute = NotRegisteredRouteImport.update({
  id: '/not-registered',
  path: '/not-registered',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/not-registered': typeof NotRegisteredRoute
  '/otp': typeof OtpRoute
  '/pin': typeof PinRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/set-pin': typeof SetPinRoute
  '/sos': typeof SosRoute
  '/support': typeof SupportRoute
  '/wallet': typeof WalletRoute
  '/booking/$id': typeof BookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/not-registered': typeof NotRegisteredRoute
  '/otp': typeof OtpRoute
  '/pin': typeof PinRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/set-pin': typeof SetPinRoute
  '/sos': typeof SosRoute
  '/support': typeof SupportRoute
  '/wallet': typeof WalletRoute
  '/booking/$id': typeof BookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/not-registered': typeof NotRegisteredRoute
  '/otp': typeof OtpRoute
  '/pin': typeof PinRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/set-pin': typeof SetPinRoute
  '/sos': typeof SosRoute
  '/support': typeof SupportRoute
  '/wallet': typeof WalletRoute
  '/booking/$id': typeof BookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/home'
    | '/login'
    | '/not-registered'
    | '/otp'
    | '/pin'
    | '/profile'
    | '/rewards'
    | '/set-pin'
    | '/sos'
    | '/support'
    | '/wallet'
    | '/booking/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/home'
    | '/login'
    | '/not-registered'
    | '/otp'
    | '/pin'
    | '/profile'
    | '/rewards'
    | '/set-pin'
    | '/sos'
    | '/support'
    | '/wallet'
    | '/booking/$id'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/home'
    | '/login'
    | '/not-registered'
    | '/otp'
    | '/pin'
    | '/profile'
    | '/rewards'
    | '/set-pin'
    | '/sos'
    | '/support'
    | '/wallet'
    | '/booking/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotRegisteredRoute: typeof NotRegisteredRoute
  OtpRoute: typeof OtpRoute
  PinRoute: typeof PinRoute
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  SetPinRoute: typeof SetPinRoute
  SosRoute: typeof SosRoute
  SupportRoute: typeof SupportRoute
  WalletRoute: typeof WalletRoute
  BookingIdRoute: typeof BookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-pin': {
      id: '/set-pin'
      path: '/set-pin'
      fullPath: '/set-pin'
      preLoaderRoute: typeof SetPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-registered': {
      id: '/not-registered'
      path: '/not-registered'
      fullPath: '/not-registered'
      preLoaderRoute: typeof NotRegisteredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotRegisteredRoute: NotRegisteredRoute,
  OtpRoute: OtpRoute,
  PinRoute: PinRoute,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  SetPinRoute: SetPinRoute,
  SosRoute: SosRoute,
  SupportRoute: SupportRoute,
  WalletRoute: WalletRoute,
  BookingIdRoute: BookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
